/**
 * AutoDraftRTWPlanBanner
 *
 * Displays a banner when the latest RTW plan for a case is an auto-generated
 * draft awaiting review. Clicking the banner navigates to the plan approval page.
 */

import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { Sparkles, ChevronRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface Props {
  caseId: string;
}

interface LatestPlanResponse {
  success: boolean;
  data: {
    plan: {
      id: string;
      status: string;
      autoGenerated?: boolean | null;
      autoGenerationConfidence?: string | number | null;
    };
  } | null;
}

export function AutoDraftRTWPlanBanner({ caseId }: Props) {
  const navigate = useNavigate();

  const { data } = useQuery<LatestPlanResponse>({
    queryKey: [`/api/rtw-plans?caseId=${caseId}`],
    enabled: !!caseId,
    retry: false,
  });

  const plan = data?.data?.plan;
  if (!plan) return null;
  if (!plan.autoGenerated) return null;
  if (plan.status !== "draft") return null;

  const rawConfidence =
    plan.autoGenerationConfidence == null
      ? null
      : typeof plan.autoGenerationConfidence === "string"
      ? parseFloat(plan.autoGenerationConfidence)
      : plan.autoGenerationConfidence;

  const confidence = rawConfidence != null && !isNaN(rawConfidence) ? rawConfidence : null;
  const showConfidence = confidence != null && confidence >= 0.5;
  const confidencePct = confidence != null ? Math.round(confidence * 100) : null;

  return (
    <button
      type="button"
      onClick={() => navigate(`/rtw/plans/${plan.id}`)}
      data-testid="auto-draft-rtw-banner"
      className="w-full text-left bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-950/30 dark:to-blue-950/30 border border-purple-200 dark:border-purple-800 rounded-lg px-4 py-3 mb-4 hover:shadow-md transition-shadow focus:outline-none focus:ring-2 focus:ring-purple-400"
    >
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-3 min-w-0">
          <div className="shrink-0 rounded-full bg-purple-100 dark:bg-purple-900 p-2">
            <Sparkles className="h-4 w-4 text-purple-600 dark:text-purple-300" />
          </div>
          <div className="min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-semibold text-sm text-purple-900 dark:text-purple-100">
                Draft RTW Plan ready for review
              </span>
              {showConfidence && confidencePct != null && (
                <Badge
                  variant="outline"
                  className="border-purple-300 text-purple-700 dark:border-purple-700 dark:text-purple-200 text-xs"
                >
                  {confidencePct}% confidence
                </Badge>
              )}
            </div>
            <p className="text-xs text-purple-700/80 dark:text-purple-200/80 truncate">
              Auto-generated based on this worker's restrictions and suitable duties.
            </p>
          </div>
        </div>
        <ChevronRight className="h-5 w-5 text-purple-600 dark:text-purple-300 shrink-0" />
      </div>
    </button>
  );
}

export default AutoDraftRTWPlanBanner;
